# Metrics
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
# ~~~ Layout ~~~
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/HashAlignment:
  Include:
    - 'lib/**/*.rb'
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
# ~~~ Lint ~~~
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
# ~~~ Metrics ~~~
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 25
# ~~~ Style ~~~
Style/AccessorGrouping:
  Enabled: false # for yard
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: false # for yard
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/FormatStringToken:
  Enabled: false # https://github.com/rubocop-hq/rubocop/issues/7944
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantReturn:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
# it's style!
Gemspec/AddRuntimeDependency:
  Enabled: false # https://github.com/rubocop/rubocop/pull/13030#discussion_r1674791776
